apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  namespace: frontend
  labels:
    app: tomcat
spec:
  containers:
    - name: tomcat
      image: tomcat:latest
      ports:
        - containerPort: 8080