apiVersion: v1
kind: Pod
metadata:
  name: redis-pod-volume
spec:
  containers:
    - name: redis-volume
      image: redis:latest
      volumeMounts:
        - name: cache-storage
          mountPath: "/my-volume"
  volumes:
    - name: cache-storage
      emptyDir: {}