apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: nginx
spec:
  template:
    metadata:
      name: pod-nginx
      labels:
        app: nginx
        env: production
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.29.0-alpine-slim
  selector:
    matchLabels:
      app: nginx
      env: production
  strategy:
    type: Recreate
  replicas: 2