apiVersion: v1
kind: Pod
metadata:
  name: pod-request-nginx
  labels:
    app: nginx-request
spec:
  containers:
    - name: nginx-request
      image: nginx:latest
      resources:
        requests:
          memory: "100Mi"
          cpu: "500m"
        limits:
          memory: "200Mi"
          cpu: "1000m"
      ports:
        - containerPort: 80