apiVersion: v1
kind: Pod
metadata:
  name: apache-pod-loadbalancer
  labels:
    app: apache-loadbalancer
spec:
  containers:
  - name: apache-container
    image: httpd:latest
    ports:
    - containerPort: 80