apiVersion: v1
kind: Service
metadata:
  name: apache-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: apache-loadbalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30081