apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    command: ["/bin/sh", "-c"]
    args:
      - echo 'Pod 1' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'
    ports:
    - containerPort: 80
