apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
spec:
  selector:
    app: nginx-proxy
  type: LoadBalancer
  ports:
  - port: 8081          # Porta interna do serviço
    targetPort: 80    # Porta do container nginx