apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: redis-daemonset
  labels:
    app: redis
spec:
  template:
    metadata:
      labels:
        apps: redis-frontend
        tier: database
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
      nodeName: kind-worker
  selector:
    matchLabels:
      apps: redis-frontend