apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-strategy
  labels:
    app: frontend-deamonset
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  template:
    metadata:
      name: daemonset-strategy
      labels:
        apps: my-app
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:latest
  selector:
    matchLabels:
      apps: my-app

