apiVersion: v1
kind: Pod
metadata:
  name: my-pod-webserver
  labels:
    apps: webserver
    tier: frontend
    
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
                     